PLACE_CHOICES = (
    ("Manpur", "Manpur"),
    ("Alipur", "Alipur"),
    ("Guraru", "Guraru"),
    ("Chakand", "Chakand"),
    ("Bela", "Bela"),
    ("Delha", "Delha"),
    ("Powerhouse", "Powerhouse"),
    ("Karimganj", "Karimganj"),
    ("Gaya", "Gaya"),
    ("Khizarsarai", "Khizarsarai"),
    ("Wazirganj", "Wazirganj"),
    ("Tekari", "Tekari"),
    ("Atri", "Atri"),
)
