# Generated by Django 5.0.7 on 2024-08-09 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField()),
                ('customer_mob_no', models.CharField(unique=True)),
                ('customer_type', models.CharField(choices=[('Mechanic', 'Mechanic'), ('Non-Mechanic', 'Non-Mechanic')])),
                ('place', models.CharField(choices=[('Manpur', 'Manpur'), ('Alipur', 'Alipur'), ('Guraru', 'Guraru'), ('Chakand', 'Chakand'), ('Bela', 'Bela'), ('Delha', 'Delha'), ('Powehouse', 'Powerhouse'), ('Karimganj', 'Karimganj')])),
                ('dues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.FloatField(default=0)),
                ('last_billed_date', models.DateTimeField(blank=True, null=True)),
                ('last_billed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('emp_name', models.CharField()),
                ('emp_contact', models.CharField(max_length=10, unique=True)),
                ('emp_aadhaar', models.CharField(max_length=12, unique=True)),
                ('emp_address', models.TextField()),
                ('emp_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emp_dues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emp_advance', models.FloatField(default=0)),
                ('emp_last_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('emp_last_payment_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_brand', models.CharField(blank=True, null=True)),
                ('item', models.CharField()),
                ('item_size', models.CharField(blank=True, null=True)),
                ('item_name', models.CharField(editable=False)),
                ('item_type', models.CharField(choices=[('MACHINING', 'MACHINING'), ('WORKSHOP', 'WORKSHOP')])),
                ('item_quantity_in_stock', models.IntegerField(default=0)),
                ('item_MRP', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_price', models.IntegerField(blank=True, null=True)),
                ('cost_price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(editable=False, unique=True)),
                ('po_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(unique=True)),
                ('make', models.CharField(choices=[('HERO', 'HERO'), ('BAJAJ', 'BAJAJ'), ('HONDA', 'HONDA'), ('YAMAHA', 'YAMAHA'), ('TVS MOTORS', 'TVS MOTORS'), ('SUZUKI', 'SUZUKI'), ('RoyalEnfield', 'RoyalEnfield')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm_name', models.CharField()),
                ('vendor_name', models.CharField()),
                ('vendor_contact_no', models.CharField(unique=True)),
                ('vendor_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(choices=[('Employee Payment', 'Employee Payment'), ('Other', 'Other')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('expense_title', models.CharField(blank=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_payments', to='svc.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_no', models.CharField(unique=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', null=True)),
                ('license_plate', models.CharField(blank=True, null=True)),
                ('total_run', models.PositiveIntegerField(blank=True, null=True)),
                ('job_completion_time', models.DateTimeField(blank=True, null=True)),
                ('total_service_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_item_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('job_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='svc.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_quantity', models.PositiveIntegerField()),
                ('item_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='svc.item')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svc.job')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_MRP', models.DecimalField(decimal_places=1, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('net_price', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svc.item')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_item', to='svc.purchaseorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('Machining', 'Machining'), ('Workshop', 'Workshop')])),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_service_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svc.job')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='svc.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='item_for_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svc.vehicle'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='svc.vendor'),
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payments', to='svc.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
