# Generated by Django 5.0.7 on 2024-08-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='customer',
        ),
    ]
