# Generated by Django 5.0.7 on 2024-08-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='place',
            field=models.CharField(choices=[('Manpur', 'Manpur'), ('Alipur', 'Alipur'), ('Guraru', 'Guraru'), ('Chakand', 'Chakand'), ('Bela', 'Bela'), ('Delha', 'Delha'), ('Powerhouse', 'Powerhouse'), ('Karimganj', 'Karimganj'), ('Gaya', 'Gaya'), ('Khizarsarai', 'Khizarsarai')]),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('HERO', 'HERO'), ('BAJAJ', 'BAJAJ'), ('HONDA', 'HONDA'), ('YAMAHA', 'YAMAHA'), ('TVS', 'TVS'), ('SUZUKI', 'SUZUKI'), ('Royal Enfield', 'Royal Enfield')]),
        ),
    ]
