# Generated by Django 5.0.7 on 2024-08-11 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0002_alter_customer_place_alter_job_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_payments', to='svc.vendor'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Employee Payment', 'Employee Payment'), ('Vendor Payment', 'Vendor Payment'), ('Other', 'Other')]),
        ),
        migrations.DeleteModel(
            name='VendorPayment',
        ),
    ]
