# Generated by Django 5.0.7 on 2024-08-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0002_remove_vehicle_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='place',
            field=models.CharField(blank=True, choices=[('Manpur', 'Manpur'), ('Alipur', 'Alipur'), ('Guraru', 'Guraru'), ('Chakand', 'Chakand'), ('Bela', 'Bela'), ('Delha', 'Delha'), ('Powerhouse', 'Powerhouse'), ('Karimganj', 'Karimganj'), ('Gaya', 'Gaya'), ('Khizarsarai', 'Khizarsarai'), ('Wazirganj', 'Wazirganj'), ('Tekari', 'Tekari'), ('Atri', 'Atri')], null=True),
        ),
    ]
