# Generated by Django 5.0.7 on 2024-08-28 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0003_alter_customer_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='primary_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_jobs', to='svc.vehicle'),
        ),
    ]
