# Generated by Django 5.0.7 on 2024-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0003_expense_vendor_alter_expense_expense_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='place',
            field=models.CharField(choices=[('Manpur', 'Manpur'), ('Alipur', 'Alipur'), ('Guraru', 'Guraru'), ('Chakand', 'Chakand'), ('Bela', 'Bela'), ('Delha', 'Delha'), ('Powerhouse', 'Powerhouse'), ('Karimganj', 'Karimganj'), ('Gaya', 'Gaya'), ('Khizarsarai', 'Khizarsarai'), ('Wazirganj', 'Wazirganj')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('HERO', 'HERO'), ('BAJAJ', 'BAJAJ'), ('HONDA', 'HONDA'), ('YAMAHA', 'YAMAHA'), ('TVS', 'TVS'), ('SUZUKI', 'SUZUKI'), ('Royal Enfield', 'Royal Enfield'), ('Mahindra', 'Mahindra'), ('Universal', 'Universal')]),
        ),
    ]
