# Generated by Django 5.0.7 on 2024-08-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0004_job_primary_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='primary_vehicle',
        ),
    ]
