# Generated by Django 5.0.7 on 2024-09-02 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0005_remove_job_primary_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='svc.vehicle'),
        ),
    ]
