# Generated by Django 5.0.7 on 2024-10-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0007_remove_job_vehicle_service_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='job',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='svc.vehicle'),
        ),
    ]
