# Generated by Django 5.0.7 on 2025-02-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0008_remove_service_vehicle_job_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='custom_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
