# Generated by Django 5.0.7 on 2025-09-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0009_service_custom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Initial balance/advance amount before any jobs', max_digits=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='initial_dues',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Initial dues amount before any jobs', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
