# Generated by Django 5.0.7 on 2025-09-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0010_customer_initial_balance_customer_initial_dues_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='initial_balance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='initial_dues',
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
