# Generated by Django 5.0.7 on 2026-02-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0011_remove_customer_initial_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='place',
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Previous dues before using MotoHub', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
