# Generated by Django 5.0.7 on 2026-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0012_remove_customer_place_customer_opening_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Previous dues before using MotoHub', max_digits=10),
        ),
    ]
