# Generated by Django 5.0.7 on 2026-02-18 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0013_vendor_vendor_opening_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the job (can be backdated)'),
        ),
    ]
