# Generated by Django 5.0.7 on 2026-02-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0014_job_job_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_billed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
