# Generated by Django 5.0.7 on 2026-02-18 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0015_alter_customer_last_billed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the PO (can be backdated)'),
        ),
    ]
