# Generated by Django 5.0.7 on 2026-02-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0016_purchaseorder_po_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='last_purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
