# Generated by Django 5.0.7 on 2026-02-25 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0017_alter_vendor_last_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobitem',
            name='custom_item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='svc.item'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('HERO', 'HERO'), ('BAJAJ', 'BAJAJ'), ('HONDA', 'HONDA'), ('YAMAHA', 'YAMAHA'), ('TVS', 'TVS'), ('SUZUKI', 'SUZUKI'), ('Royal Enfield', 'Royal Enfield'), ('Mahindra', 'Mahindra'), ('Piaggio', 'Piaggio'), ('Universal', 'Universal')]),
        ),
    ]
