# Generated by Django 5.0.7 on 2026-02-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('svc', '0019_customerpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPayment',
        ),
    ]
